# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Feature-2 CI check

on:
  push:
    branches: [ feature-2-sonar ]
  pull_request:
    branches: [ feature-2-sonar ]
  workflow_dispatch:

jobs:
  Install-Requeriments:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.0b1-buster
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: install requeriments
      run: |
        python -m pip install --no-cache-dir pip==22.0.4

  Sonar-Check:
    name: Sonar-Check
    needs: [Install-Requeriments]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
  Veracode-SAST-Pipeline-Scan:
    runs-on: ubuntu-latest
    needs: [Install-Requeriments]
    container:
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: scan 
        run: |
          zip -r -v pygoat.zip . -i '*.py' '*.js' '*.html'  
          java -jar /opt/veracode/pipeline-scan.jar -vid "${{ secrets.VID }}" -vkey "${{ secrets.VKEY }}" -f pygoat.zip -aid "1242124" -p "PyGoat-Showroom"   
        continue-on-error: true  
        
  Push-image: 
    runs-on: ubuntu-latest
    needs: [Sonar-Check, Veracode-SAST-Pipeline-Scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test Deploy
        run: | 
          docker pull pygoat/pygoat
          docker images 
          sleep 5
