# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Veracode Scan

on:
  push:
    branches: [ feature-1 ]
  pull_request:
    branches: [ feature-1 ]

  workflow_dispatch:

jobs:
  Install-Requeriments:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.0b1-buster
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: pip install
        run: |
          python -m pip install --no-cache-dir pip==22.0.4
